### PR TITLE
Hubot Is Typing

### PR DESCRIPTION
**Pull request by RIAlizer**
Added Hubot "Is Typing" feedback
https://github.com/slackhq/hubot-slack/issues/259

### CODE REVIEW

**Comment by dasilvacontin** [comment]
@RIAlizer why did you close it?

**Comment by dasilvacontin** [comment]
Ok, I see.

**Comment by RIAlizer** [comment]
@dasilvacontin The command `_send({ type: "typing")` actually works, but I need to fix tests and add more logic.

**Comment by dasilvacontin** [comment]
But it will be some kind of method you have to manually invoke, I hope? Most common use case is to fake typing when processing a command is gonna take a while.

**Comment by tlytg456** [comment]
@aoberoi Our bot may do some complete work which spends a long time, so we want to give users some feedback while we calculate the results, besides the "xxx is typing" or some other message. We think the "typing" feedback is suitable. But why the project remove this feature?

**Comment by tlytg456** [comment]
@aoberoi Thanks for your patience, I have known that and find the best ways to solve them

**Pull request closed without merging**
