### PR TITLE
Listen to user_change & brain loaded event

### PR DESCRIPTION
**Pull request by rizkiarm**
This will add a listener for ``user_change`` and hubot brain ``loaded`` event. Both listener will reload the user data in hubot brain to maintain integrity.

### CODE REVIEW

**Comment by DEGoodmanWilson** [comment]
Howdy, thanks for this! Looking over it now!

**Comment by DEGoodmanWilson** [comment]
One thing that we will want is test coverage over this new feature, so you know!

**Comment by johnagan** [comment]
I'm pretty sure v3 of the node-sdk stores the users in the dataStore immediately after authenticating and updates it accordingly. It's worth another set of 👀 though.

https://github.com/slackhq/node-slack-sdk/tree/5c8d3bdbcc38a71ca45d372444ce5f79178de557/lib/data-store/message-handlers

Additionally, we only used this to convert IDs <> mentions, which I think we can now handle in the API with `parse` and `link_names`

**Comment by rizkiarm** [comment]
@DEGoodmanWilson: Okay, will do it when I have time to spare

@johnagan: Confirmed, dataStore stores all kinds of information upon authenticating, I'll try to change the implementation accordingly, soon. 

Btw, any other idea on how to provide the other hubot scripts access to important data (users, channels, etc) in the dataStore without using using hubot brain?

**Comment by DEGoodmanWilson** [comment]
I find myself suddenly concerned about the two layers of cacheing involved. I wonder if there is a more general mechanism available that would simply have the brain object pass through queries about Slack objects to dataStore instead of trying to keep the two in sync?

**Comment by rizkiarm** [comment]
It would be great if there is such mechanism. However, as for now I don't have any other ideas to implement this functionality without sacrificing the compatibility issues that might arise with the other scripts (e.g: hubot-brain, etc). Based on my limited observation on several other hubot adapters, it seems that almost all of them use this kind of approach, which might indicates that this is the preferred way to handle this things (?).

**Comment by DEGoodmanWilson** [comment]
Looking at the Campfile adapter (and taking it as canonical), it provides a small number of functions for querying Campfire entities (users, rooms) that simply pass through to the underlying APIs, rather than using the brain as a cacheing layer. We've decided that exposing the `node-slack-sdk` client object is the right thing to do, exposing the existing cache that it provides directly.

Part of the motivation for this is that the brain is meant as a persistent store of data for Hubot scripts, but that the data that you are wanting to store there is not meant in large part to be persisted but merely cached, as most of it is volatile. So, I am sorry to say, I am going to turn down your PR as not being what we consider to be in the spirit of the projects' goals and aims.

**Pull request closed without merging**
