### PR TITLE
Handle reaction_added messages

### PR DESCRIPTION
**Pull request by mbland**
* [x] I've read and understood the [Contributing guidelines](./CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](./CODE_OF_CONDUCT.md).
* [x] I've been mindful about doing atomic commits, adding documentation to my changes, not refactoring too much.
* [x] I've a descriptive title and added any useful information for the reviewer. Where appropriate, I've attached a screenshot and/or screencast (gif preferrably).
* [x] I've written tests to cover the new code and functionality included in this PR.
* [x] I've read, agree to, and signed the [Contributor License Agreement (CLA)](https://docs.google.com/a/slack-corp.com/forms/d/1q_w8rlJG_x_xJOoSUMNl7R35rkpA7N6pUkKhfHHMD9c/viewform).

#### PR Summary

Handle reaction_added messages

Converts reaction_added messages to TextMessages before passing them to Hubot. Used to implement behavior needed by 18F/hubot-slack-github-issues and depends on behavior from slackhq/node-slack-sdk#96, which may be out-of-date by now. I'll take a look at the latest version and report back when I get a chance tonight or tomorrow, unless someone else already has context and beats me to it.

#### Related Issues

Supercedes and closes #271. Also pertains to #251.

#### Test strategy

Unit tests to validate the new `SlackBot.reactionAdded` method as part of the existing `Handling incoming messages` suite.

cc: @johnagan @mtlewis @patcon @afeld @ccostino @skehlet @MidnightLightning @stevecat @DEGoodmanWilson

### CODE REVIEW

**Comment by DEGoodmanWilson** [comment]
Hello @mbland ! This looks quite nice, thank you for taking the time to update your PR!

However, I have one complaint. Rather than emitting a `TextMessage`, the current paradigm is to emit a new kind of message, so that clients can select what kinds of events they respond to. Look at bot.coffee:137–_ff._ I would recommend creating a `ReactionMessage` that specifies what happened in a structured way (what reaction? what message? was it added or removed?) rather than overloading `TextMessage` to accomplish this.

Thoughts?

**Comment by mtlewis** [comment]
@mbland thanks so much for picking this back up!

**Comment by mbland** [comment]
@DEGoodmanWilson I was secretly hoping you'd suggest something like that. Done.

The reason I held back originally (other than trying to keep parity with the existing #271 while I re-familiarized myself with the code) was because I noticed all the existing message types are imported from the `hubot` npm. Would the long-term plan, then, be to add this message type upstream? I'm happy to send out another PR to github/hubot to do that if you think that makes sense.

**Comment by mbland** [comment]
Also, looking back at slackhq/node-slack-sdk#96 and https://github.com/slackhq/node-slack-sdk/blob/3.4.0/lib/clients/rtm/client.js, it looks like the `reaction_added` and `reaction_removed` events are emitted by default, as with every other event type. Consequently, everything should "just work", modulo pushing the `ReactionMessage` class upstream.

**Comment by johnagan** [comment]
LGTM 👍 

great work!

**Comment by DEGoodmanWilson** [comment]
Yeah, this is great. I would advise against adding these types upstream in Hubot. Not all messaging services provide this kind of functionality, and to my mind at least, platform-specific features should remain with the adapter. Because, let's be honest, a Hubot script or plugin that makes use of this message type is simply not going to work on another service.

Merging this in, will release…_soon_. I promise.

**Comment by mbland** [comment]
Cool, thanks! (And I was tilting towards the same conclusion re: pushing `ReactionMessage` upstream.)

**Comment by mbland** [comment]
Looks like this just got pushed in [v4.1.0](https://github.com/slackhq/hubot-slack/releases/tag/v4.1.0). Thanks, @DEGoodmanWilson and @johnagan!

**Comment by neufeldtech** [comment]
Hi there @mbland, 
I've scanned the code in your PR, but I'm still unsure on how to actually implement reaction handling in a hubot script.  Would you care to provide a simple "hello world" example on how to get hubot to listen for reaction_added messages? Thanks!

**Comment by mbland** [comment]
@neufeldtech I'll try to get to it in the next day or two. Feel free to ping me by Friday if I haven't posted back.

FWIW, the original hack was to [hook into the `receiveMiddleware` mechanism](https://github.com/mbland/hubot-slack-github-issues/blob/1.0.2/scripts/slack-github-issues.js#L23-L33), and when a message came through, [check the message type (`reaction_added`) and item type](https://github.com/mbland/hubot-slack-github-issues/blob/1.0.2/lib/middleware.js#L67-L71). I need to update that plugin as well, so I'll try to both knock it out and the "Hello, World!" example at the same time.

**Comment by mbland** [comment]
@neufeldtech OK, here you go: https://github.com/mbland/hubot-slack-reaction-example

**Comment by neufeldtech** [comment]
@mbland Thanks! I'll be sure to take a look at this.

**Comment by mbland** [comment]
Not to drag this thread out too long, but...I've already updated [the example script](https://github.com/mbland/hubot-slack-reaction-example/blob/master/scripts/handle-reaction.coffee) to be even smaller and easier to follow.

And @DEGoodmanWilson: Do you think it'd be worth patching on a `robot.react` during `SlackBot.run`, so that clients won't have to `require` the `ReactionMessage` type or define the `(message) -> message instanceof ReactionMessage` matcher at all? (Happy to supply the PR myself, of course.)

**Comment by DEGoodmanWilson** [comment]
@mbland That might be a good idea, actually!

**Comment by mbland** [comment]
OK, just filed #363. Anyone who's still interested can subscribe to that PR.

**Comment by mbland** [comment]
FYI @neufeldtech (and others), with the merge of #363 and release of v4.2.0, `robot.react` is now live. I've updated my [hubot-slack-reaction-example](https://github.com/mbland/hubot-slack-reaction-example) to use it (as well as trimmed down the instructions), so you may want to look at it again.

**Pull request merged**
