### PR TITLE
No longer exit on client close

### LINKED ISSUE #127: SlackBot should reconnect instead of terminating the process
When the slack connection closes, or when an error occurs (which `SlackBot` currently handles by terminating the process after 1 second), the adapter should reconnect after a short timeout instead of terminating the process.

For precedent, the bundled Campfire adapter reconnects after 5 seconds when its streaming HTTP connection closes.

### PR DESCRIPTION
**Pull request by davefp**
Fixes #127

### CODE REVIEW

**Comment by davefp** [comment]
I've been unable to 'really' test this as simulating network problems by simply severing my local wifi connection results in an error on reconnect which also causes the process to exit.

Suggestions on better tools/strategies to test this are welcome! In the meantime I'm going to be running my branch on a production hubot to see if any problems arise.

**Comment by austinpray** [comment]
@evansolomon can we get a release with this included?

**Comment by ddffx** [comment]
@evansolomon any plan to put it in a release?

**Comment by goofansu** [comment]
:+1: Need a release

**Comment by goofansu** [comment]
Hubot says `Slack client closed, waiting for reconnect` but cannot connect. I've wait for hours.

**Comment by goofansu** [comment]
It is terminated.  I ran it on my Macbook Pro.

```
[Tue May 19 2015 13:50:12 GMT+0800 (CST)] INFO Connecting...
[Tue May 19 2015 13:50:32 GMT+0800 (CST)] INFO Logged in as yybot of 上海页游网络科技, but not yet connected
[Tue May 19 2015 13:50:38 GMT+0800 (CST)] INFO Slack client now connected
[Tue May 19 2015 13:50:39 GMT+0800 (CST)] INFO Using default redis on localhost:6379
[Tue May 19 2015 13:50:39 GMT+0800 (CST)] INFO Data for hubot brain retrieved from Redis
[Tue May 19 2015 13:52:43 GMT+0800 (CST)] ERROR Last pong is too old: 14.638
[Tue May 19 2015 13:52:43 GMT+0800 (CST)] INFO Reconnecting in 1000ms
[Tue May 19 2015 13:52:44 GMT+0800 (CST)] INFO Attempting reconnect
[Tue May 19 2015 13:52:44 GMT+0800 (CST)] INFO Connecting...
[Tue May 19 2015 13:53:03 GMT+0800 (CST)] INFO Slack client closed, waiting for reconnect
[Tue May 19 2015 13:53:05 GMT+0800 (CST)] INFO Logged in as yybot of 上海页游网络科技, but not yet connected
[Tue May 19 2015 13:53:07 GMT+0800 (CST)] INFO Slack client now connected
[Tue May 19 2015 13:53:07 GMT+0800 (CST)] INFO Using default redis on localhost:6379
[Tue May 19 2015 13:53:07 GMT+0800 (CST)] INFO Data for hubot brain retrieved from Redis
[Tue May 19 2015 14:00:17 GMT+0800 (CST)] ERROR Last pong is too old: 14.705
[Tue May 19 2015 14:00:17 GMT+0800 (CST)] INFO Reconnecting in 1000ms
[Tue May 19 2015 14:00:18 GMT+0800 (CST)] INFO Attempting reconnect
[Tue May 19 2015 14:00:18 GMT+0800 (CST)] INFO Connecting...
[Tue May 19 2015 14:00:47 GMT+0800 (CST)] INFO Slack client closed, waiting for reconnect
[Tue May 19 2015 14:02:44 GMT+0800 (CST)] ERROR Received error "ECONNRESET"
[Tue May 19 2015 14:02:44 GMT+0800 (CST)] ERROR undefined
[Tue May 19 2015 14:02:44 GMT+0800 (CST)] ERROR Exiting in 1 second
[Tue May 19 2015 14:02:44 GMT+0800 (CST)] INFO Reconnecting in 2000ms
```

**Comment by yoblin** [comment]
Tested this fix and it works, but then the listeners do not reinitialize or something. The bot rejoins the channel but does not respond to any commands.

**Comment by technicalpickles** [comment]
cc https://github.com/slackhq/hubot-slack/issues/228 for tracking getting this released

**Comment by kimamula** [comment]
> Hubot says `Slack client closed, waiting for reconnect` but cannot connect. I've waited for hours.

I ran into the same problem.
It is likely we have to wait until https://github.com/slackhq/node-slack-client/issues/5 to be solved.

**Pull request merged**
