### PR TITLE
Add https proxy support

### PR DESCRIPTION
**Pull request by GrandPubba**

### CODE REVIEW

**Comment by jhunthrop** [comment]
Can this be merged? I am currently maintaining a fork with this enhancement.

**Comment by dillten** [comment]
Need this as well.

**Comment by haraldringvold** [comment]
I hope this will get merged. I had problems getting hubot-slack to work and it seems that GrandPubbas work works. I suspect there will be other people having the same problems.

**Comment by rhysd** [comment]
:+1: I also need this.

**Comment by tcnksm** [comment]
We need this as well

**Comment by keke** [comment]
Please merge this.

**Comment by jonfreedman** [comment]
+1

**Comment by jonfreedman** [comment]
In addition to taking this merge I would be grateful for support for custom certificates to support the use case where hubot is behind a https proxy which intercepts ssl.  It's possible to get this running with NODE_TLS_REJECT_UNAUTHORIZED="0" but that's not ideal.

**Pull request merged**
